[workspace]
members = [
    "nucypher-core",
    "nucypher-core-python",
    "nucypher-core-wasm",
]

# Prevents `local exceed maximum` error
# See: https://github.com/rustwasm/wasm-pack/issues/981
[profile.test]
opt-level = 1