[package]
name = "nucypher-core"
version = "0.8.0"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
edition = "2021"
license = "GPL-3.0-only"
description = "Nucypher network core datastructures"
repository = "https://github.com/nucypher/nucypher-core/tree/main/nucypher-core"
readme = "README.md"
categories = ["cryptography", "no-std"]

[dependencies]
umbral-pre = { version = "0.10.0", features = ["serde"] }
ferveo = { package = "ferveo-pre-release", version = "0.1.0-alpha.8" }
serde = { version = "1", default-features = false, features = ["derive"] }
generic-array = "0.14"
sha3 = "0.10"
rmp-serde = "1"
serde_with = "1.14"
hex = "0.4"
x25519-dalek = { version="2.0.0-rc.2", features = ["serde"] }
chacha20poly1305 = "0.10.1"

[dev-dependencies]
rand_core = "0.6.4"