[package]
name = "nucypher-core"
version = "0.2.0"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
edition = "2021"
license = "GPL-3.0-only"
description = "Nucypher network core datastructures"
repository = "https://github.com/nucypher/nucypher-core/tree/master/nucypher-core"
readme = "README.md"
categories = ["cryptography", "no-std"]

[dependencies]
umbral-pre = { version = "0.6", features = ["serde-support"] }
serde = { version = "1", default-features = false, features = ["derive"] }
generic-array = "0.14"
typenum = "1.14"
sha3 = "0.10"
rmp-serde = "0.15"
k256 = { version = "0.11", default-features = false, features = ["ecdsa"]}
signature = "1.5"
serde_with = "1.14"
